### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by GuidoPreite** [VinnyDyn/CompleteForm#1]
No Licenses are specified for this repository, can one be added? instructions https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by VinnyDyn** [comment]
Hi Guido, done! 👍🏻

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Guido Preite <notifications@github.com>
Enviado: Tuesday, November 19, 2019 8:33:43 AM
Para: VinnyDyn/CompleteForm <CompleteForm@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [VinnyDyn/CompleteForm] License is missing (#1)


No Licenses are specified for this repository, can one be added? instructions https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.github.com%2Fen%2Fgithub%2Fbuilding-a-strong-community%2Fadding-a-license-to-a-repository&data=02%7C01%7C%7C7691f1fafdc140b32d3708d76ce45540%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637097600240529460&sdata=bikx%2F0cMMim9MPke3oBLH3c9XKDz9qfixruj2LYcPxI%3D&reserved=0>
